#!/bin/bash
# 部署檢查清單 & 數據庫遷移指南

echo "=========================================="
echo "SpamKiller v2.0 部署前檢查清單"
echo "=========================================="

echo ""
echo "✅ 代碼變更完成"
echo "   - 修復違規紀錄表結構（統一使用 violation_logs）"
echo "   - 增強日誌系統，加入嵌入模型狀態"
echo "   - 添加管理員標記正常訊息機制 (/normal 命令)"
echo "   - 改善 /config 命令，提升用戶友好性"
echo "   - 添加控制頻道配置選項"
echo ""

echo "📋 需要執行的數據庫遷移步驟："
echo ""
echo "1️⃣ 在 Supabase SQL Editor 執行遷移腳本:"
echo "   文件: migration_violations_cleanup.sql"
echo "   - 刪除舊的 violations 表"
echo "   - 添加高效索引"
echo ""

echo "2️⃣ 在 Supabase SQL Editor 執行以下 SQL："
echo "   正常訊息表 & RPC 函數已包含在 supabase_schema.sql 中"
echo "   需執行 match_normal_patterns RPC 函數創建"
echo ""

echo "3️⃣ 驗證表結構:"
echo "   SELECT table_name FROM information_schema.tables"
echo "   WHERE table_schema = 'public';"
echo ""
echo "   應包含:"
echo "   ✓ whitelist"
echo "   ✓ spam_patterns"
echo "   ✓ normal_patterns"
echo "   ✓ config"
echo "   ✓ violation_logs"
echo ""

echo "4️⃣ 驗證 RPC 函數:"
echo "   SELECT routine_name FROM information_schema.routines"
echo "   WHERE routine_schema = 'public';"
echo ""
echo "   應包含:"
echo "   ✓ match_spam_patterns"
echo "   ✓ match_normal_patterns"
echo ""

echo "📦 部署步驟"
echo "1. npm install (確保依賴最新)"
echo "2. npx wrangler deploy"
echo "3. 設定 Telegram webhook (若需重新設定)"
echo ""

echo "🔧 新增指令說明"
echo "   /normal   - (回覆訊息) 標記訊息為正常，機器人學習此特徵"
echo "   /config   - (無參數) 顯示當前配置及幫助信息"
echo ""

echo "✨ 新增配置選項"
echo "   /config control_channel [ID] - 設定控制頻道"
echo "   (優先級: 控制頻道 > 轉發頻道 > 全局)"
echo ""

echo "✅ 驗證清單"
echo "   [ ] 數據庫遷移完成"
echo "   [ ] 新的 RPC 函數已建立"
echo "   [ ] 部署成功"
echo "   [ ] 機器人在測試群組中回應"
echo "   [ ] /normal 命令可正確執行"
echo "   [ ] /config 無參數顯示幫助信息"
echo ""

echo "=========================================="
echo "部署前請確認所有項目已完成"
echo "=========================================="
